# Chọn image Maven làm base image để build ứng dụng
FROM maven:3.8.4-jdk-11-slim AS build

# Đặt thư mục làm việc trong container
WORKDIR /app

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Chạy lệnh build ứng dụng
RUN mvn clean install

# Sử dụng image Java để chạy ứng dụng
FROM openjdk:11-jre-slim

# Đặt thư mục làm việc
WORKDIR /app

# Sao chép file JAR đã build từ image Maven vào container
COPY --from=build /app/target/School_Medical_Management_System-0.0.1-SNAPSHOT.jar /app/School_Medical_Management_System.jar

# Mở cổng 8080
EXPOSE 8080

# Chạy ứng dụng
ENTRYPOINT ["java", "-jar", "/app/School_Medical_Management_System.jar"]
